### ISSUE TITLE
Feature request: Add more endpints

### ISSUE THREAD

**Issue by vdun** [alanvardy/gpto#266]
https://app.anakin.ai
https://www.perplexity.ai
...

**Comment by alanvardy** [comment]
Perplexity uses an OpenAI client API so it can be used by changing the endpoint and using the appropriate API key. This usage is already supported.

https://www.perplexity.ai/hub/faq/pplx-api

Thank you for the issue!

**Comment by vdun** [comment]
Here there are other free endpoints: https://github.com/aandrew-me/tgpt
