### ISSUE TITLE
Consider renaming

### ISSUE THREAD

**Issue by Explosion-Scratch** [alanvardy/gpto#272]
See: https://openai.com/index/hello-gpt-4o/

**Comment by alanvardy** [comment]
Please provide additional information and reopen the issue, why would I consider renaming the project?

Renaming it would mean hardship for all those currently using it, and I would lose the users that don't migrate to the new name.

**Comment by Explosion-Scratch** [comment]
> Renaming it would mean hardship for all those currently using it, and I would lose the users that don't migrate to the new name.

Hence "Consider" 🙃 - Now that OpenAI has stolen your name it causes some confusion, especially as this has nothing to do with their new GPTo model
